unixbench:
  vm_groups:
    default:
      cloud: AWS
      os_type: centos7
      vm_spec:
        AWS:
          machine_type: c5.2xlarge
          image: ami-0e8286b71b81c3cc1
          zone: eu-central-1
          boot_disk_size: 8
