speccpu2006_charon_ssp:
  vm_groups:
    default:
      cloud: AWS
      os_type: centos7
      vm_spec:
        AWS:
          machine_type: c5.2xlarge
          image: ami-041e264e582b25875
          zone: eu-central-1
