iperf_charon_ssp:
  vm_groups:
    vm_1:
      cloud: AWS
      os_type: centos7
      vm_spec:
        AWS:
          machine_type: c5d.2xlarge
          image: ami-05f8b95e14027a73d
          zone: eu-central-1
      disk_spec:
        AWS:
          disk_type: local # Instance storage - fixed size on EC2
          # disk_size: 50
          mount_point: /scratch
    vm_2:
      cloud: AWS
      os_type: centos7
      vm_spec:
        AWS:
          machine_type: c5d.2xlarge
          image: ami-05f8b95e14027a73d
          zone: eu-central-1
      disk_spec:
        AWS:
          disk_type: local # Instance storage - fixed size on EC2
          # disk_size: 50
          mount_point: /scratch
